### ISSUE TITLE
release-v0.1.0 and release tag r1.0 are not pointing to same commit

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ShortMessageService#13]
**Problem description**

release-v0.1.0 and release tag r1.0 are not pointing to same commit (the branch was created already one week ago).

Beyond that 

**Expected behavior**

release-v0.1.0 could be deleted to resolve the mismatch. The release branch is no longer needed within the new API release process.

**Alternative solution**

Ensure that 
https://github.com/camaraproject/ShortMessageService/tree/r0.1 and
https://github.com/camaraproject/ShortMessageService/tree/release-v0.1.0
are the same commit.

**Additional context**

https://wiki.camaraproject.org/display/CAM/API+Release+Process

**Comment by hdamker** [comment]
Related to #11 but different topic now, after there is the release

**Comment by hdamker** [comment]
> Hi @hdamker - I do not have permissions to delete release-v0.1.0. Therefore, I raised a PR to merge main branch changes to release-v0.1.0. Please check.

Sorry for that ... I have removed the branch protection rule for now and  renamed the branch to release-1.0, but maybe it is easier to delete it as the tag `r1.0` and and the branch `release-1.0` are still not pointing to the same commit.

As said, release branches are not planned to be part of the new release process.

Best Regards
Herbert

**Comment by a-ramit** [comment]
Thanks @hdamker. I have deleted the branch now. Pls check and close the issue.

Regards,
Ramit

**Comment by hdamker** [comment]
Great @a-ramit, will close. 

You might want to consider to clean up the patch branches which were merged 2 months ago.
