### ISSUE TITLE
Codeowner file not yet valid

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ShortMessageService#5]
**Problem description**

The codeowner file is not yet valid, as @tcchiba @a-ramit need first accept the invitation to collaborate within this repository.

**Expected action**

@tcchiba @a-ramit to accept the invitation I have sent.

**Comment by a-ramit** [comment]
I have accepted the invitation.

**Comment by hdamker** [comment]
CODEOWNER file is valid now, thanks @a-ramit and @tcchiba.
Closing the issue.
